from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser, AllowAny, IsAuthenticated
from django.contrib.auth.models import User
from django.conf import settings
from rest_framework_simplejwt.tokens import RefreshToken
from google.oauth2 import id_token
from google.auth.transport import requests
import requests as requests_lib
import time
import os

from .models import Report, Notification
from .serializers import ReportSerializer, UserSerializer, NotificationSerializer
from .services import get_gemini_report, get_osm_poi_density, calculate_priority

class GoogleLoginView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        token = request.data.get('token')
        if not token:
            return Response({'error': 'No token provided'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            # 1. Try to verify as ID Token (GoogleLogin component)
            try:
                idinfo = id_token.verify_oauth2_token(
                    token, requests.Request(), settings.GOOGLE_OAUTH2_CLIENT_ID
                )
            except Exception:
                # 2. Fallback: Try as Access Token (useGoogleLogin hook)
                userinfo_res = requests_lib.get(
                    'https://www.googleapis.com/oauth2/v3/userinfo',
                    headers={'Authorization': f'Bearer {token}'}
                )
                if not userinfo_res.ok:
                    return Response({'error': 'Invalid Google Token (Check origins)'}, status=status.HTTP_400_BAD_REQUEST)
                idinfo = userinfo_res.json()

            email = idinfo['email']
            first_name = idinfo.get('given_name', idinfo.get('name', ''))
            last_name = idinfo.get('family_name', '')

            # Get or Create the user
            user, created = User.objects.get_or_create(username=email, defaults={
                'email': email,
                'first_name': first_name,
                'last_name': last_name
            })

            # OWNER AUTO-PROMOTION: If this is you, make sure you are Staff/Admin
            if email.lower() == 'parmeetb2002@gmail.com':
                if not user.is_staff or not user.is_superuser:
                    user.is_staff = True
                    user.is_superuser = True
                    user.save()

            # Issue JWT
            refresh = RefreshToken.for_user(user)
            
            return Response({
                'access': str(refresh.access_token),
                'refresh': str(refresh),
                'user': {
                    'email': user.email,
                    'is_staff': user.is_staff
                }
            })

        except ValueError as e:
            print(f"DEBUG: Google Login Auth Error: {str(e)}")
            return Response({'error': 'Invalid token', 'details': str(e)}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            print(f"DEBUG: Critical Backend Login Error: {str(e)}")
            return Response({'error': 'Backend Setup Error', 'details': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

class MeView(APIView):
    """
    Returns the current authenticated user's live profile.
    Used to refresh is_staff status without requiring re-login.
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        return Response({
            'email': user.email,
            'first_name': user.first_name,
            'is_staff': user.is_staff,
            'is_superuser': user.is_superuser,
        })

class AnalyzeView(APIView):
    """
    Analyzes an image without saving a report. Used for live preview.
    """
    authentication_classes = [] # Total bypass of auth checks
    permission_classes = [AllowAny] # Unlocked for better reliability

    def post(self, request):
        image_file = request.FILES.get('image')
        if not image_file:
            return Response({'error': 'No image provided'}, status=status.HTTP_400_BAD_REQUEST)
        
        analysis = get_gemini_report(image_file)
        return Response(analysis)

class ReportViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = ReportSerializer

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return Report.objects.all().order_by('-created_at')
        return Report.objects.filter(user=user).order_by('-created_at')

    def perform_create(self, serializer):
        image = serializer.validated_data.get('image')
        lat = serializer.validated_data.get('latitude')
        lon = serializer.validated_data.get('longitude')
        
        # 1. Use the description provided by the user (or generated by AI earlier)
        ai_description = self.request.data.get('ai_description', 'Processing...')
        severity_score = int(self.request.data.get('severity_score', 5))

        # 2. Get Population Density (Infrastructure Context)
        density = get_osm_poi_density(lat, lon)
        
        # 3. Final Priority Logic
        priority = calculate_priority(severity_score, density)
        
        serializer.save(
            user=self.request.user,
            ai_description=ai_description,
            severity_score=severity_score,
            density_index=density,
            priority_level=priority
        )

    def perform_update(self, serializer):
        old_status = self.get_object().status
        new_status = self.request.data.get('status')
        
        instance = serializer.save()
        
        if old_status != 'Resolved' and new_status == 'Resolved':
            # Create Notification for the citizen who reported the issue
            if instance.user:
                Notification.objects.create(
                    user=instance.user,
                    report=instance,
                    message=f"Good news! Your report #{instance.id} has been marked as Resolved by an official. Evidence of the fix has been uploaded."
                )

class NotificationViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = NotificationSerializer

    def get_queryset(self):
        return Notification.objects.filter(user=self.request.user).order_by('-created_at')

    def mark_as_read(self, request, pk=None):
        notification = self.get_object()
        notification.is_read = True
        notification.save()
        return Response({'status': 'notification marked as read'})

class UserListView(APIView):
    """
    Lists all users for admin management. Accessible only to staff.
    """
    permission_classes = [IsAdminUser]

    def get(self, request):
        users = User.objects.all().order_by('-date_joined')
        serializer = UserSerializer(users, many=True)
        return Response(serializer.data)

class ToggleStaffStatusView(APIView):
    """
    Toggles is_staff status for a user. Accessible ONLY to the owner.
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # SECURITY: Strictly restrict this to the owner's email
        if request.user.email.lower() != 'parmeetb2002@gmail.com':
            return Response({'error': 'Unauthorized. Only the owner can manage admin status.'}, status=status.HTTP_403_FORBIDDEN)

        user_id = request.data.get('user_id')
        try:
            target_user = User.objects.get(id=user_id)
            # Toggle staff status
            target_user.is_staff = not target_user.is_staff
            target_user.save()
            return Response({
                'id': target_user.id,
                'email': target_user.email,
                'is_staff': target_user.is_staff,
                'message': f"Updated {target_user.email} status to {'Admin' if target_user.is_staff else 'Citizen'}"
            })
        except User.DoesNotExist:
            return Response({'error': 'User not found'}, status=status.HTTP_404_NOT_FOUND)

class ChatbotView(APIView):
    """
    Proxies user messages to Gemini REST API for the civic help chatbot.
    Uses direct HTTP requests to avoid SDK version dependency issues.
    """
    authentication_classes = []
    permission_classes = [AllowAny]

    SYSTEM_PROMPT = (
        "You are CivicBot, a friendly assistant for the Bareilly Civic Reporting Platform. "
        "Help citizens understand: how to submit infrastructure reports (potholes, broken lights, "
        "garbage, illegal dumping), how the AI triage system works, how priority levels are assigned, "
        "how to track reports and check resolution status, and general civic information about Bareilly. "
        "Keep responses concise and friendly. If asked about unrelated topics, politely redirect. "
        "Always encourage citizens - their reports help improve Bareilly's infrastructure."
    )

    def post(self, request):
        user_message = request.data.get('message', '').strip()
        history = request.data.get('history', [])  # list of {role, text}

        if not user_message:
            return Response({'error': 'No message provided'}, status=status.HTTP_400_BAD_REQUEST)

        keys_to_try = [
            os.environ.get("CHATBOT_GEMINI_API_KEY"),
            os.environ.get("GEMINI_API_KEY")
        ]
        valid_keys = [k for k in keys_to_try if k and k.strip()]
        
        if not valid_keys:
            return Response({'reply': 'API key configuration missing on server.'}, status=status.HTTP_200_OK)

        try:
            # Build contents list for multi-turn conversation
            contents = []

            if not history:
                contents.append({
                    "role": "user",
                    "parts": [{"text": f"{self.SYSTEM_PROMPT}\n\nUser question: {user_message}"}]
                })
            else:
                first_text = history[0].get('text', '') if history else ''
                contents.append({
                    "role": "user",
                    "parts": [{"text": f"{self.SYSTEM_PROMPT}\n\nUser question: {first_text}"}]
                })
                for turn in history[1:]:
                    role = "user" if turn.get('role') == 'user' else "model"
                    contents.append({
                        "role": role,
                        "parts": [{"text": turn.get('text', '')}]
                    })
                contents.append({
                    "role": "user",
                    "parts": [{"text": user_message}]
                })

            payload = {
                "contents": contents,
                "generationConfig": {
                    "maxOutputTokens": 500,
                    "temperature": 0.7
                }
            }

            last_error_code = None
            last_error_text = ""

            # Strictly use gemini-2.5-flash as explicitly requested
            models_to_try = ['gemini-2.5-flash']
            
            for api_key in valid_keys:
                for model_name in models_to_try:
                    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
                    res = requests_lib.post(url, json=payload, timeout=20)

                    if res.status_code == 200:
                        data = res.json()
                        reply_text = data['candidates'][0]['content']['parts'][0]['text']
                        return Response({'reply': reply_text})
                    
                    last_error_code = res.status_code
                    last_error_text = res.text[:200]
                    print(f"Gemini API error {last_error_code} with key/model ({model_name}): {last_error_text}")

            # If all keys and models failed, format a highly readable error
            if last_error_code == 429:
                return Response({'reply': "I am currently receiving too many messages (Quota Exceeded). Let me catch my breath—please try again in a minute!"}, status=status.HTTP_200_OK)
            elif last_error_code == 403:
                return Response({'reply': "My API key lacks proper permissions. The server admin needs to enable the Generative Language API in Google Cloud."}, status=status.HTTP_200_OK)
            else:
                return Response({'reply': f"I ran into a server communication error ({last_error_code}). Please try again later."}, status=status.HTTP_200_OK)

        except Exception as e:
            print(f"ChatbotView exception: {type(e).__name__}: {e}")
            return Response(
                {'reply': f"Server error: {type(e).__name__}: {str(e)[:200]}"},
                status=status.HTTP_200_OK
            )
