# Generated by Django 5.1.5 on 2026-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_user_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='density_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
